config/routes.rb
Portal::Application.routes.draw do

  devise_for :users

  resources :workflow_errors

  match '/about_portal' => 'about_portal#index'
  match '/cookies' => 'about_portal#cookies'
  match '/about' => 'about_portal#index'

  resources :workflow_ports do
    member do
      post "download"
    end
  end

  resources :password_resets

  resources :oauth_consumers do
    member do
      get :callback
      get :callback2
      match 'client/*endpoint' => 'oauth_consumers#client'
    end
  end

  resources :announcements

  resources :users, :except => [:create, :destroy, :show]

  mount TavernaPlayer::Engine, :at => "/"

  resources :workflows do
    resources :runs, :controller => "TavernaPlayer::Runs", :except => [:edit, :update]
    member do
      put "make_public"
      put "make_private"
      post "save_custom_inputs"
      post "save_custom_outputs"
      post "save_custom_errors"
    end
  end

  #*****************************************************
  # mapping for the redirection when downloading a workflow
  match 'workflows/:id/download/', :controller => 'workflows', :action => 'download'
  #*****************************************************

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'welcome#index'

end

app/controllers/workflows_controller.rb
# Copyright (c) 2012-2013 Cardiff University, UK.
# Copyright (c) 2012-2013 The University of Manchester, UK.
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the names of The University of Manchester nor Cardiff University nor
#   the names of its contributors may be used to endorse or promote products
#   derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Authors
#     Abraham Nieva de la Hidalga
#     Finn Baccall
#     Robert Haines
#     Alan Williams
#
# Synopsis
#
# BioVeL Portal is a prototype interface to Taverna Server which is
# provided to support easy inspection and execution of workflows.
#
# For more details see http://www.biovel.eu
#
# BioVeL is funded by the European Commission 7th Framework Programme (FP7),
# through the grant agreement number 283359.
class WorkflowsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show, :download]
  before_filter :get_workflows, :only => :index
  before_filter :get_workflow, :only => :show

  # GET /workflows
  # GET /workflows.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @workflows }
    end
  end

  # GET /workflows/1
  # GET /workflows/1.json
  def show
    @selected_tab = params[:selected_tab]
    @sources, @source_descriptions = @workflow.get_inputs
    @custom_inputs = @workflow.get_custom_inputs
    @custom_outputs = @workflow.get_custom_outputs
    @sinks, @sink_descriptions = @workflow.get_outputs
    @processors = @workflow.get_processors
    @ordered_processors = @workflow.get_processors_in_order
    @workflow_errors = @workflow.get_errors
    @workflow_error_codes = @workflow.get_error_codes

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @workflow }
    end
  end

  # GET /workflows/new
  # GET /workflows/new.json
  def new
    search_by =""
    if !params[:search].nil?
      search_by = params[:search].strip
    end
    @workflow = Workflow.new
    @me_workflows = []
    @consumer_tokens=getConsumerTokens
    @services=OAUTH_CREDENTIALS.keys-@consumer_tokens.collect{|c| c.class.service_name}
    if (!search_by.nil? && search_by!="")
     if @consumer_tokens.count > 0
       # search for my experiment workflows
       @workflows = getmyExperimentWorkflows(@me_workflows, URI::encode(search_by))
     end
   end
   respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @workflow }
    end
  end

  # GET /workflows/1/edit
  def edit
    @workflow = Workflow.find(params[:id])
  end

  # POST /workflows
  # POST /workflows.json
  def create
    if(!params[:workflow_name].nil?)
      create_from_my_exp(params)
    else
      create_from_upload(params)
    end
  end
  def create_from_upload(params)
    @workflow = Workflow.new(params[:workflow])
    @consumer_tokens=getConsumerTokens
    @services=OAUTH_CREDENTIALS.keys-@consumer_tokens.collect{|c| c.class.service_name}
    respond_to do |format|
      @workflow.get_details_from_model
      @workflow.user_id = current_user.id
      # the model uses t2flow to get the data from the workflow file
      if @workflow.save
        format.html { redirect_to @workflow, :notice => 'Workflow was successfully added.' }
        format.json { render :json => @workflow, :status => :created, :location => @workflow }
      else
        format.html { render :action => "new", :notice => 'Workflow cannot be added.' }
        format.json { render :json => @workflow.errors, :status => :unprocessable_entity }
      end
    end
  end
  def create_from_my_exp(params)
    @workflow = Workflow.new()
    content_uri = params[:workflow_uri]
    wf_name = params[:workflow_name]
    wf_name = wf_name.downcase.gsub(" ","_").gsub(".", "") + '.t2flow'
    link_uri = params[:workflow_link]
    @consumer_tokens=getConsumerTokens
    @services=OAUTH_CREDENTIALS.keys-@consumer_tokens.collect{|c| c.class.service_name}
    # get the workflow using token
    if @consumer_tokens.count > 0
      token = @consumer_tokens.first.client
      doc = REXML::Document.new(response.body)
      response=token.request(:get, content_uri)

      directory = "/tmp"
      File.open(File.join(directory, wf_name), 'wb') do |f|
        f.puts response.body
      end
    end
    @workflow.me_file = File.open(File.join(directory, wf_name), 'r')
    @workflow.workflow_file = wf_name
    @workflow.my_experiment_id = link_uri
    respond_to do |format|
      @workflow.get_details_from_model
      @workflow.user_id = current_user.id
      # the model uses t2flow to get the data from the workflow file
      if @workflow.save
        format.html { redirect_to @workflow, :notice => 'Workflow was successfully added.' }
        format.json { render :json => @workflow, :status => :created, :location => @workflow }
      else
        format.html { render :action => "new", :notice => 'Workflow cannot be added.' }
        format.json { render :json => @workflow.errors, :status => :unprocessable_entity }
      end
    end
  end
  # PUT /workflows/1
  # PUT /workflows/1.json
  def update
    @workflow = Workflow.find(params[:id])

    respond_to do |format|
      if @workflow.update_attributes(params[:workflow])
        format.html { redirect_to @workflow, :notice => 'Workflow was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @workflow.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /workflows/1
  # DELETE /workflows/1.json
  def destroy
    @workflow = Workflow.find(params[:id])
    @workflow.delete_files
    @workflow.destroy

    respond_to do |format|
      format.html { redirect_to workflows_url }
      format.json { head :no_content }
    end
  end

  def download
    @workflow = Workflow.find(params[:id])
    path = @workflow.workflow_filename
    filetype = 'application/xml'
    send_file path, :type=>filetype , :name => @workflow.name
  end

  def make_public
    @workflow = Workflow.find(params[:id])
    @workflow.shared = true
    @workflow.save!
    redirect_to :back
  end

  def make_private
    @workflow = Workflow.find(params[:id])
    @workflow.shared = false
    @workflow.save!
    redirect_to :back
  end

  def save_custom_inputs
    action = params[:commit]
    @workflow = Workflow.find(params[:id])
    @inputs, @input_desc = @workflow.get_inputs
    if action == 'Save'
      save_inputs
    elsif action == 'Reset'
      reset_inputs
    end
    respond_to do |format|
      format.html { redirect_to @workflow, :notice => 'Workflow inputs updated'}
      format.json { head :no_content }
     end
  end

  def save_inputs
    @input_desc.each do |indiv_in|
      i_name = indiv_in[0]
      file_for_i = "file_for_"+i_name
      customise_i = "customise_"+i_name
      display_i = "display_for_"+i_name
      if ((params[:file_uploads].include? i_name) &&
          params[:file_uploads][customise_i] == "1") &&
          ((params[:file_uploads].include? file_for_i) ||
           (params[:file_uploads][i_name] != ""))
        # verify if customised input exists
        wfps = WorkflowPort.where("port_type = ? and name = ?", "1", i_name)
        if wfps.empty?
          @wfp = WorkflowPort.new()
        else
          @wfp = wfps[0]
        end
        #get values for customised input
        @wfp.workflow_id = @workflow.id
        @wfp.port_type = 1 # 1 = input
        @wfp.name = i_name
        @wfp.display_control_id = params[:file_uploads][display_i]
        if params[:file_uploads].include? file_for_i
          #save file
          @wfp.file_content = params[:file_uploads][file_for_i].tempfile
          @wfp.sample_file =  params[:file_uploads][file_for_i].original_filename
          @wfp.sample_file_type = params[:file_uploads][file_for_i].content_type
        end
        if params[:file_uploads][i_name] != ""
          #save value
          @wfp.sample_value = params[:file_uploads][i_name]
        end
        #save the customisation
        @wfp.save
      elsif params[:file_uploads][customise_i] == "0"
        # reset port customisation
        wfps = WorkflowPort.where("port_type = ? and name = ?", "1", i_name)
        unless wfps.empty?
          @wfp = wfps[0]
          @wfp.delete_files
          @wfp.destroy
        end
      end
    end
  end

  def reset_inputs
    @input_desc.each do |indiv_in|
      i_name = indiv_in[0]
      wfps = WorkflowPort.where("port_type = ? and name = ?", "1", i_name)
      unless wfps.empty?
        @wfp = wfps[0]
        @wfp.delete_files
        @wfp.destroy
      end
    end
  end

  def save_custom_outputs

app/helpers/workflows_helper.rb
# Copyright (c) 2012-2013 Cardiff University, UK.
# Copyright (c) 2012-2013 The University of Manchester, UK.
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the names of The University of Manchester nor Cardiff University nor
#   the names of its contributors may be used to endorse or promote products
#   derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Authors
#     Abraham Nieva de la Hidalga
#     Robert Haines
#     Finn Bacall
#     Alan Williams
#
# Synopsis
#
# BioVeL Taverna Lite  is a prototype interface to Taverna Server which is
# provided to support easy inspection and execution of workflows.
#
# For more details see http://www.biovel.eu
#
# BioVeL is funded by the European Commission 7th Framework Programme (FP7),
# through the grant agreement number 283359.
module WorkflowsHelper
end

app/views/workflows/_add_workflow_myexp_search.html.erb
<%
# Copyright (c) 2012-2013 Cardiff University, UK.
# Copyright (c) 2012-2013 The University of Manchester, UK.
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the names of The University of Manchester nor Cardiff University nor
#   the names of its contributors may be used to endorse or promote products
#   derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Authors
#     Abraham Nieva de la Hidalga
#     Finn Bacall
#
# Synopsis
#
# BioVeL Taverna Lite  is a prototype interface to Taverna Server which is
# provided to support easy inspection and execution of workflows.
#
# For more details see http://www.biovel.eu
#
# BioVeL is funded by the European Commission 7th Framework Programme (FP7),
# through the grant agreement number 283359.
%>
<%= render :partial => 'oauth_consumers/connection' %>
<% unless @consumer_tokens.empty? %>
<div id="search_my_exp">
  <%= form_tag new_workflow_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>


    <% if !@me_workflows.nil? %>
    <!-- Accordion -->
    <h2 class="demoHeaders">Results:  <%= @me_workflows.count %> Workflows found</h2>
    <div id="accordion_results">
      <% @me_workflows.each do |workflow| %>
        <h3>
          Name: <%= workflow.name %>
        </h3>
        <div>
          <div style="float:right;">
            <%= link_to workflows_path(:workflow_uri=>workflow.content_uri,
                                          :workflow_name=>workflow.name,
                                          :workflow_link=>workflow.uri),
                                    :method => :post,
                                    :class=>"link_img"  do %>
              <%= image_tag "cog_add.png",
                :height => "25",:alt=>"get this workflow",
                :title=>"get this workflow" %>
              get workflow
            <% end %>
            <%= link_to  workflow.uri,:id=>workflow.id,:class=>"link_img" do %>
              <%= image_tag "myexperiment.png",
                :height => "25",:alt=>"view on my experiment",
                :title=>"view on my experiment",:style=>"aling:middle;" %>
              more details
            <% end %>
          </div>
          <%=render :partial=>'add_workflow_myexp_detail',
                    :locals => {:workflow=>workflow} %>

        </div>
      <% end %>
    </div>

    <% else %>
      <h2>No workflows found</h2>
    <%end%>
</div>


<%end%>

app/views/workflows/_workflows.html.erb
<%
# Copyright (c) 2012-2013 Cardiff University, UK.
# Copyright (c) 2012-2013 The University of Manchester, UK.
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the names of The University of Manchester nor Cardiff University nor
#   the names of its contributors may be used to endorse or promote products
#   derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Authors
#     Abraham Nieva de la Hidalga
#     Robert Haines
#
# Synopsis
#
# BioVeL Taverna Lite  is a prototype interface to Taverna Server which is
# provided to support easy inspection and execution of workflows.
#
# For more details see http://www.biovel.eu
#
# BioVeL is funded by the European Commission 7th Framework Programme (FP7),
# through the grant agreement number 283359.
%>
<table id="private_workflows">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author(s)</th>
      <% if current_user.admin -%>
        <th>Owner</th>
      <% end -%>
      <th>Uploaded</th>
      <th>Updated</th>
      <th>Operations</th>
    </tr>
  </thead>
  <tbody>
  <% @workflows.each do |workflow| %>
    <tr>
      <td title="<%= workflow.description %>" alt="<%= workflow.description %>">
        <dl class="wf_snip">
          <dt><%= link_to workflow.title, workflow  %></dt>
          <dd><%= workflow.description.nil? ? "" : workflow.description[0,79]+"..." %></dd>
        </dl>
    </td>
    <td>
      <%= workflow.author %>
    </td>
    <% if current_user.admin -%>
      <td>
        <% if workflow.user_id !=0 %>
          <%=User.find(workflow.user_id).name %>
        <%else%>
          No user
        <%end%>
      </td>
    <% end -%>
    <td><%= workflow.created_at.strftime("%Y/%m/%d %H:%M") %></td>
    <td><%= workflow.updated_at.strftime("%Y/%m/%d %H:%M") %></td>
    <td>
    <div title="Run workflow" alt="Run workflow" style="float:left">
      <%= link_to 'Run', {:controller => 'runs' ,
          :action => 'new_run', :id => workflow.id}, :class => "link_img" %>
    </div>
    <div title="Download workflow" alt="Download workflow" style="float:left">
      <%= link_to 'Download', {:controller => 'workflows' ,
          :action => 'download', :id => workflow.id}, :class => "link_img" %>
    </div>
    <div title="toggle workflow sharing" alt="toggle workflow sharing" style="float:left">
      <% if workflow.shared? -%>
        <%= link_to "Make private", make_private_workflow_path(workflow), :method => :put, :class => "link_img"%>
      <% else -%>
        <%= link_to "Make public", make_public_workflow_path(workflow), :method => :put, :class => "link_img" %>
      <% end -%>
    </div>
    <div title="Remove workflow" alt="Remove workflow" style="float:left">
      <%= link_to 'Remove', workflow, :class => "link_img_rem",
          :method => :delete,
          :data => { :confirm => 'Remove this workflow: ' +
                       workflow.title.to_s + "?" } %>
    </div>    </td>
  </tr>
  <% end -%>
  </tbody>
</table>

app/views/workflows/index.html.erb
<%
# Copyright (c) 2012-2013 Cardiff University, UK.
# Copyright (c) 2012-2013 The University of Manchester, UK.
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the names of The University of Manchester nor Cardiff University nor
#   the names of its contributors may be used to endorse or promote products
#   derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Authors
#     Abraham Nieva de la Hidalga
#     Robert Haines
#
# Synopsis
#
# BioVeL Portal is a prototype interface to Taverna Server which is
# provided to support easy inspection and execution of workflows.
#
# For more details see http://www.biovel.eu
#
# BioVeL is funded by the European Commission 7th Framework Programme (FP7),
# through the grant agreement number 283359.
%>
<% content_for :title, "BioVeL Portal - Workflows"%>
<h1>Workflows</h1>
<p>
  This page shows workflows that you can execute on BioVeL Portal
</p>
<p>
  A workflow is the automation of series of data analysis (steps) to process
  data (from small to very large-scale), be that from one's own research and/or
  from existing sources.
</p>

<% if !current_user.nil? %>
  <div title="Add a new workflow" alt="Add a new workflow">
    <%= link_to 'Add Workflow', new_workflow_path, :class => "link_img" %>
  </div>
  <h2>Private</h2>
  <%= render 'workflows' %>
<% end -%>

<% if @shared_workflows.count != 0 -%>
  <h2>Public</h2>
<% if current_user.nil? -%>
  <p>
    <%= link_to 'Register', new_user_registration_path %> to upload your own workflows and to
    search for workflows on
    <%= link_to 'my experiment', 'http://www.myexperiment.org' %>
  </p>
<%end%>
  <%= render 'workflows_public' %>
<% end -%>
<br/><br/>